# Generated by Django 5.1.6 on 2025-02-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_flagship',
            field=models.BooleanField(default=False),
        ),
    ]
